Web/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    path('schedule/', include('schedule.urls')),
    path('', RedirectView.as_view(url='/schedule/')),    
    path('admin/', admin.site.urls)
]

schedule/urls.py
from django.urls import path

from . import views
from . import viewslocation
from . import viewsactivity
from . import viewsdependency
from . import viewsreport

app_name = 'schedule'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:schedule_id>/', views.detail, name='detail'),
    path('<int:schedule_id>/update', views.update, name='update'),
    path('<int:schedule_id>/delete', views.delete, name='delete'),
    path('<int:schedule_id>/deleteindex', views.deleteindex, name='deleteindex'),
    path('location/<int:schedule_id>/index', viewslocation.index, name='index'),
    path('location/<int:location_id>/detail', viewslocation.detail, name='detail'),
    path('location/<int:location_id>/update', viewslocation.update, name='update'),
    path('location/<int:location_id>/delete', viewslocation.delete, name='delete'),
    path('location/<int:location_id>/deleteindex', viewslocation.deleteindex, name='deleteindex'),
    path('activity/<int:schedule_id>', viewsactivity.index, name='index'),
    path('activity/<int:activity_id>/detail', viewsactivity.detail, name='detail'),
    path('activity/<int:activity_id>/delete', viewsactivity.delete, name='delete'),
    path('activity/<int:activity_id>/update', viewsactivity.update, name='update'),
    path('activity/<int:activity_id>/deleteindex', viewsactivity.deleteindex, name='deleteindex'),
    path('activity/<int:activity_id>/getsuccessors', viewsactivity.getsuccessors, name='getsuccessors'),
    path('dependency/<int:activity_id>', viewsdependency.index, name='index'),
    path('dependency/<int:dependency_id>/detail', viewsdependency.detail, name='detail'),
    path('dependency/<int:dependency_id>/update', viewsdependency.update, name='update'),
    path('dependency/<int:dependency_id>/delete', viewsdependency.delete, name='delete'),
    path('dependency/<int:dependency_id>/deleteindex', viewsdependency.deleteindex, name='deleteindex'),
    path('report/<int:schedule_id>/', viewsreport.index, name='index'),
    path('reportdays/<int:schedule_id>/', viewsreport.daysindex, name='daysindex'),
    path('reportstochastic/<int:schedule_id>/', viewsreport.stochasticindex, name='stochasticindex'),
]

schedule/models.py
from django.db import models

schedule/models/Activity.py
"""All functionality related to activities"""

from schedule.models import Common, Dependency


class Activity:
    def __init__(self, **entries):
        self.__dict__.update(entries)

    Id = ""
    Name = ""
    Duration = 0
    ScheduleId = 0
    LocationId = 0
    ActivityTypeId = 0
    Initial = ""
    Pos = 0
    StartDate = ""      # calculated field not stored in the database
    EndDate = ""        # calculated field not stored in the database
    NewDuration = 0     # calculated field not stored in the database


class ActivityType:
    def __init__(self, **entries):
        self.__dict__.update(entries)

    Id = ""
    Name = ""


class ActivityService:
    @classmethod
    def GetById(cls, activityId):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "SELECT * FROM activity WHERE Id=%s"
                cursor.execute(sql, (str(activityId)))
                result = cursor.fetchone()
                activity = None if result is None else Activity(**result)
                return activity

        finally:
            connection.close()

    @classmethod
    def GetByLocationId(cls, locationId):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "SELECT * FROM activity WHERE LocationId=%s"
                cursor.execute(sql, (str(locationId)))
                results = cursor.fetchmany(cursor.rowcount)
                activityList = [Activity(**result) for result in results]
                return activityList

        finally:
            connection.close()

    @classmethod
    def GetPredecessors(cls, activityId, scheduleId):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = """SELECT * FROM activity
                       WHERE ScheduleId = %s AND
                       activity.Pos < (SELECT pos FROM activity WHERE activity.Id = %s)"""

                cursor.execute(sql, (str(scheduleId), str(activityId)))
                results = cursor.fetchmany(cursor.rowcount)
                activityList = [Activity(**result) for result in results]
                return activityList

        finally:
            connection.close()

    @classmethod
    def GetByScheduleId(cls, scheduleId):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = """SELECT activity.*, activity_type.Name AS ActivityTypeName, location.Name AS LocationName
                      FROM activity
                      INNER JOIN activity_type ON activity.ActivityTypeId = activity_type.Id
                      INNER JOIN location ON activity.LocationId = location.Id
                      WHERE activity.ScheduleId=%s
                      ORDER BY pos"""

                cursor.execute(sql, (str(scheduleId)))
                results = cursor.fetchmany(cursor.rowcount)
                # Convert list of dicts to list of classes
                activityList = [Activity(**result) for result in results]

                return activityList

        finally:
            connection.close()

    @classmethod
    def GetActivityTypes(cls):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = """SELECT * FROM activity_type
                       ORDER BY pos"""
                cursor.execute(sql)
                results = cursor.fetchmany(cursor.rowcount)
                # Convert list of dicts to list of classes
                activityTypeList = [ActivityType(**result) for result in results]

                return activityTypeList

        finally:
            connection.close()

    @classmethod
    def Update(cls, activity):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = """UPDATE `activity` SET `ScheduleId` = %s, `LocationId` = %s, `ActivityTypeId` = %s, `Name` = %s, 
                      `Duration` = %s
                      WHERE Id = %s"""

                cursor.execute(sql, (activity.ScheduleId, activity.LocationId, activity.ActivityTypeId, activity.Name,
                                     activity.Duration, activity.Id))
                connection.commit()
        finally:
            connection.close()

    @classmethod
    def Add(cls, activity, scheduleId):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "SET @top:= (SELECT MAX(Pos) + 1 FROM activity WHERE scheduleId = %s)"
                cursor.execute(sql, (scheduleId))

                sql = "SET @top = IF(@TOP IS NULL, 1, @TOP)"
                cursor.execute(sql)

                sql = """INSERT INTO `activity` (`Name`, `Duration`, `ScheduleId`, `LocationId`, `ActivityTypeId`,
                      `Pos`) 
                      VALUES (%s, %s, %s, %s, %s, @top)"""

                cursor.execute(sql, (activity.Name, activity.Duration, activity.ScheduleId, activity.LocationId,
                                     activity.ActivityTypeId))
                connection.commit()
                return cursor.lastrowid
        finally:
            connection.close()

    @classmethod
    def UpdatePositions(cls, scheduleId):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "SET @pos:=0"
                cursor.execute(sql)

                sql = """UPDATE activity
                       SET Pos=@pos:=@pos+1
                       WHERE ScheduleId = %s
                       ORDER BY Pos"""

                cursor.execute(sql, (scheduleId))
                connection.commit()
        finally:
            connection.close()

    @classmethod
    def SetNewPos(cls, newPosId, activityId, scheduleId):
        newPos = 0

        if newPosId != 0:
            activity = cls.GetById(newPosId)
            newPos = activity.Pos + 0.5
        else:
            newPos = 0.5

        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "UPDATE activity SET Pos=%s where Id = %s"
                cursor.execute(sql, (newPos, activityId))
                connection.commit()
        finally:
            connection.close()

        cls.UpdatePositions(scheduleId)
        cls.DeleteSuccessors(activityId, int(newPos + 0.5))

    @classmethod
    def Delete(cls, activity_id):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "DELETE FROM dependency WHERE ActivityId = %s"
                cursor.execute(sql, (activity_id))
                connection.commit()

                sql = "DELETE FROM dependency WHERE PredActivityId = %s"
                cursor.execute(sql, (activity_id))
                connection.commit()

                sql = "DELETE FROM activity WHERE Id = %s"
                cursor.execute(sql, (activity_id))
                connection.commit()
        finally:
            connection.close()

    @classmethod
    def GetSuccessors(cls, activityId, newPosId):
        connection = Common.getconnection()
        newPos = 0

        if newPosId != 0:
            activity = cls.GetById(newPosId)
            newPos = activity.Pos

        try:
            with connection.cursor() as cursor:
                sql = """SELECT dependency.* FROM dependency 
                       INNER JOIN activity ON activity.Id = dependency.PredActivityId
                       WHERE dependency.ActivityId = %s AND activity.Pos > %s"""

                cursor.execute(sql, (activityId, newPos))
                results = cursor.fetchmany(cursor.rowcount)
                dependencyList = [Dependency.Dependency(**result) for result in results]

                return dependencyList

        finally:
            connection.close()

    @classmethod
    def DeleteSuccessors(cls, activityId, position):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "DELETE dependency FROM dependency  \
                       INNER JOIN activity ON dependency.PredActivityId = activity.Id \
                       WHERE dependency.ActivityId = %s AND activity.Pos > %s"

                cursor.execute(sql, (activityId, position))
                connection.commit()

        finally:
            connection.close()

schedule/models/Common.py
from django.conf import settings
import pymysql

def getconnection():
    return pymysql.connect(host=settings.DATABASES['default']['HOST'],
                           user=settings.DATABASES['default']['USER'],
                           password=settings.DATABASES['default']['PASSWORD'],
                           db=settings.DATABASES['default']['NAME'],
                           charset='utf8mb4',
                           cursorclass=pymysql.cursors.DictCursor)

schedule/models/Location.py
"""All functionality related to locations"""

from schedule.models import Common


class Location:
    def __init__(self, **entries):
        self.__dict__.update(entries)

    Id = 0
    ScheduleId = 0
    Name = ''
    Lat = 0.0
    Long = 0.0


class LocationService:
    @classmethod
    def GetByScheduleId(cls, ScheduleId):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "SELECT * FROM location WHERE ScheduleId=%s"
                cursor.execute(sql, (str(ScheduleId)))
                results = cursor.fetchmany(cursor.rowcount)
                locationList = [Location(**result) for result in results]
                return locationList

        finally:
            connection.close()

    @classmethod
    def GetById(cls, Id):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "SELECT * FROM location WHERE Id=%s"
                cursor.execute(sql, (str(Id)))
                result = cursor.fetchone()
                location = None if result is None else Location(**result)
                return location

        finally:
            connection.close()

    @classmethod
    def Add(cls, location):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = """INSERT INTO `location` (`ScheduleId`, `Name`, `Lat`, `Long`)
                       VALUES (%s, %s, %s, %s)"""

                cursor.execute(sql, (location.ScheduleId, location.Name, location.Lat, location.Long))
                connection.commit()
        finally:
            connection.close()

    @classmethod
    def Update(cls, location):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = """UPDATE `location` SET `Name` = %s, `ScheduleId` = %s, `Lat` = %s, `Long` = %s
                       WHERE Id = %s"""

                cursor.execute(sql, (location.Name, location.ScheduleId, location.Lat, location.Long, location.Id))
                connection.commit()
        finally:
            connection.close()

    @classmethod
    def Delete(cls, location_id):
        connection = Common.getconnection()

        try:
            with connection.cursor() as cursor:
                sql = "DELETE FROM location WHERE Id = %s"
                cursor.execute(sql, (location_id))
                connection.commit()
        finally:
            connection.close()

schedule/views.py
import time

from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader

from schedule.models import Schedule, ScheduleService, ActivityService, LocationService


def index(request):
    demoMode = settings.DEMO_MODE
    scheduleService = ScheduleService
    schedules = scheduleService.GetAll()

    template = loader.get_template('schedule/index.html')
    context = {'schedules': schedules, 'demoMode': demoMode}
    return HttpResponse(template.render(context, request))


def detail(request, schedule_id):
    scheduleService = ScheduleService
    schedule = Schedule
    statusTypes = scheduleService.GetStatusTypes()
    demoMode = settings.DEMO_MODE

    if schedule_id != 0:
        schedule = scheduleService.GetById(schedule_id)

    template = loader.get_template('schedule/detail.html')
    context = {'schedule': schedule, 'scheduleId': schedule_id, 'demoMode': demoMode, 'statusTypes': statusTypes}
    return HttpResponse(template.render(context, request))


def update(request, schedule_id):
    schedule = Schedule()
    schedule.Id = request.POST['id']
    schedule.Name = request.POST['name']
    schedule.StartDateDisplay = request.POST['startdate']
    schedule.StartDate = time.strptime(schedule.StartDateDisplay, "%d/%m/%Y")
    schedule.StatusTypeId = request.POST['statustype']
    schedule.StatusDateDisplay = request.POST.get('statusdate', '')
    schedule.StatusDate = time.strptime(schedule.StatusDateDisplay,
                                        "%d/%m/%Y") if schedule.StatusDateDisplay != '' else None

    schedule = UpdateWorkingDays(request, schedule)
    scheduleService = ScheduleService

    if schedule_id != 0:
        scheduleService.Update(schedule)
    else:
        scheduleService.Add(schedule)

    return HttpResponseRedirect('/schedule')


def deleteindex(request, schedule_id):
    activityService = ActivityService
    locationService = LocationService

    # Need to check to see if there are dependencies related to this activity
    activities = activityService.GetByScheduleId(schedule_id)
    locations = locationService.GetByScheduleId(schedule_id)

    template = loader.get_template('schedule/delete.html')
    context = {'activities': len(activities), 'scheduleId': schedule_id, 'locations': len(locations)}
    return HttpResponse(template.render(context, request))


def delete(request, schedule_id):
    scheduleService = ScheduleService
    scheduleService.Delete(schedule_id)
    return HttpResponseRedirect("/")


def IsChecked(dict, item):
    if dict.get(item, 0) == '':
        return True
    else:
        return False


def UpdateWorkingDays(request, schedule):
    for item in range(0, 6):
        schedule.__dict__["WorkingDay" + str(item)] =  IsChecked(request.POST, 'workingday' + str(item))

    return schedule

schedule/templates/schedule/delete.html
{% extends "base.html" %}

{% block title %}Schedule Delete{% endblock %}

{% block content %}

<br />
<div class="container">
    <h3>
        Delete Schedule
    </h3>

    <br /   >
    <div class="alert alert-danger">
        <p>         
            {% if activities > 0 %}
            This activity has {{activities}} activities, so cannot be deleted.
            {% elif locations > 0 %}
            This activity has {{locations}} location(s), so cannot be deleted.
            {% else %}
            Are you sure you wish to delete this schedule?
            
            Press delete if you want to continue.
            {% endif %}
        </p>
    </div>

    <form action="/schedule/{{scheduleId}}/delete" method="post" data-parsley-validate="">
        {% csrf_token %}
        <input type="hidden" name="schedule_id" value="{{scheduleId}}" />
        {% if activities == 0 and locations == 0 %}
        <button type="submit" class="btn btn-primary">Delete</button>
        {% endif %}
        <a class="btn btn-secondary" href="/">Cancel</a>
    </form> 
</div>

{% endblock %}

schedule/templates/schedule/detail.html
{% extends "base.html" %}

{% block title %}Schedule Edit{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/">Schedule List</a></li>
<li class="breadcrumb-item active" aria-current="page">Schedule</li>
{% endblock %}

{% block content %}

<div class="container">
    <form action="/schedule/{{schedule.Id}}/update" method="post" data-parsley-validate="">
        {% csrf_token %}

        <input type="hidden" name="id" value="{{schedule.Id}}" />
                
        <div class="form-group w-50">
            <label for="inputName">Name</label>
            <input type="text" class="form-control" name="name" id="inputName" value="{{schedule.Name}}" required="" />
        </div>

        <div class="form-group w-25">
            <label for="inputStartDate">Project Start Date</label>
            <input type="text" class="form-control" id="inputStartDate" name="startdate" value="{{schedule.StartDateDisplay}}" data-parsley-datecheck required="" />
        </div>

        <div class="form-group w-50">
            <label for="activity-type">Project Status</label>
            <select class="form-control form-control-sm" name="statustype" id="selectStatus">
                {% for status in statusTypes %}
                <option value="{{status.Id}}" {% if schedule.StatusTypeId == status.Id %}selected{% endif %}>{{status.Name}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group w-25">
            <label for="inputStatusDate">Project Status Date</label>
            <input type="text" class="form-control" id="inputStatusDate" name="statusdate" value="{{schedule.StatusDateDisplay}}" data-parsley-datecheck />
        </div>

        <div class="form-group">
            <div class="form-group">
                <label class="form-check-label" for="check0">
                    Working Days
                </label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="workingday0" value="" {% if schedule.WorkingDay0 %} checked="checked" {% endif %} data-parsley-mincheck="1">
                <label class="form-check-label" for="check0">
                    Monday
                </label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="workingday1" value="" {% if schedule.WorkingDay1 %} checked="checked" {% endif %}>
                <label class="form-check-label" for="check0">
                    Tuesday
                </label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="workingday2" value="" {% if schedule.WorkingDay2 %} checked="checked" {% endif %}>
                <label class="form-check-label" for="check0">
                    Wednesday
                </label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="workingday3" value="" {% if schedule.WorkingDay3 %} checked="checked" {% endif %}>
                <label class="form-check-label" for="check0">
                    Thursday
                </label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="workingday4" value="" {% if schedule.WorkingDay4 %} checked="checked" {% endif %}>
                <label class="form-check-label" for="check0">
                    Friday
                </label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="workingday5" value="" {% if schedule.WorkingDay5 %} checked="checked" {% endif %}>
                <label class="form-check-label" for="check0">
                    Saturday
                </label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="workingday6" value="" {% if schedule.WorkingDay6 %} checked="checked" {% endif %}>
                <label class="form-check-label" for="check0">
                    Sunday
                </label>
            </div>
        </div>

        {% if scheduleId != 0 %}
        <div class="form-group">
            <a class="btn btn-secondary" data-toggle="tooltip" title="Manage the locations where construction will be carried out" href="/schedule/location/{{schedule.Id}}/index">Edit project locations</a>
            <a class="btn btn-secondary" data-toggle="tooltip" title="Manage this schedule's activities and dependencies" href="/schedule/activity/{{schedule.Id}}">Edit project activities</a>
        </div>
        {% endif %}
        
        <div class="form-group">
            {% if demoMode == False %}
            <button type="submit" class="btn btn-primary">Save</button>
            {% endif %}
            <a data-toggle="tooltip" title="Discard any changes and return to the schedule list" class="btn btn-secondary" href="{% url 'schedule:index' %}">Cancel</a>
        </div>
        
        <div class="form-group">
            <div id="divider">
            </div>

        {% if scheduleId != 0 %}
        <h5>Schedule Reports</h5>
        {% if schedule.StatusTypeId != 3 %}
        <h6>Forwards (for weather-aware project planning)</h6>
        <div class="form-group">
            <a class="btn btn-secondary" data-toggle="tooltip" title="Show the planned and weather affected schedule" href="/schedule/report/{{schedule.Id}}?reporttype=2">Gantt Chart</a>
            <a class="btn btn-secondary" href="/schedule/reportstochastic/{{schedule.Id}}">Stochastic Project Duration</a>
            <a class="btn btn-secondary" href="/schedule/reportdays/{{schedule.Id}}">Project Duration by start date</a>
        </div>
        {% endif %}
        
        {% if schedule.StatusTypeId != 1 %}
        <h6>Backwards (for retrospective weather-related as-built projects)</h6>
        <div class="form-group">        
            <a class="btn btn-secondary" data-toggle="tooltip" title="Show the planned and weather affected schedule" href="/schedule/report/{{schedule.Id}}?reporttype=4">Gantt Chart</a>
            <a class="btn btn-secondary" href="/schedule/reportstochastic/{{schedule.Id}}/?type=4">Stochastic Project Duration</a>
        </div>  
        {% endif %}
        
        {% endif %}
        <div class="form-group">
        </div>
    </form>
</div>

{% endblock %}

{% block javascript %}
    <script>
        $('#selectStatus').on('change', function() {
            statusChanged(this.value)
        });

        function statusChanged(status) {
            var inputStatusDate = document.getElementById("inputStatusDate");

            if (status == 2)
                    inputStatusDate.removeAttribute("readonly");
            else
                    inputStatusDate.setAttribute("readonly", true);
        }

        $(document).ready(function() {
            var status = $('#selectStatus').val();
            statusChanged(status);
        });
    </script>
{% endblock %}

schedule/templates/schedule/index.html
{% extends "base.html" %}

{% block title %}Schedules{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page">Schedule List</li>
{% endblock %}

{% block content %}

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Start Date</th>                
                <th scope="col">Status</th>                
            </tr>
        </thead>
    {% for schedule in schedules %}
    <tr>
        <td>
            {{ schedule.Name }}
        </td>
        <td>
            {{ schedule.StartDate }}
        </td>
        <td>
            {{ schedule.StatusName }}
        </td>
        <td>
            <a data-toggle="tooltip" title="View the Gantt Chart" href="/schedule/report/{{schedule.Id}}/?reporttype=2&fromschedules=1">Gantt...</a>
        </td>            
        <td>
            <a data-toggle="tooltip" title="Edit the schedule and view reports" href="/schedule/{{schedule.Id}}">Edit...</a>
        </td>            
        {% if demoMode == False %}
        <td>
            <a href="/schedule/{{schedule.Id}}/deleteindex">Delete...</a>
        </td>            
        {% endif %}
    </tr>
    {% endfor %}
</table>

<a class="btn btn-secondary" href="/schedule/0">Add a new schedule...</a>

<div style="margin-top:100px">
<div id="divider"></div>
    <p>
    This is a website application for considering the influence of weather in UK construction projects. This project was funded by the Natural Environment Research Council (NERC) under the Environmental Risks to Infrastructure Innovation Programme (ERIIP) with Grant number NE/R008876/1 at the University of Reading. Weather data were supplied by the UK Met Office (MIDAS data set).
    </p>

    <p>
    Principal Investigator Dr Stefán Thor Smith, Co-Investigator Dr Pablo Ballesteros-Pérez, Research Assistant/Computer Programmer Peter C.
    </p>
</div>

</div>
{% endblock %}